using System;
using System.Collections.Generic;
using LcdMod.Common.Imaging;
using VRageMath;
using ArgumentOutOfRangeException = LcdMod.Common.Exceptions.ArgumentOutOfRangeException;

namespace LcdMod.Client.Modules.Cartography
{
    /// <summary>
    /// One square cubemap mip stored directly as native Space Engineers colors.
    /// The LCD app can sample this without converting through a text palette.
    /// </summary>
    public sealed class PlanetColorMip
    {
        readonly Color[] _colors;

        internal PlanetColorMip(int resolution, Color[] colors)
        {
            if (resolution <= 0)
                throw new ArgumentOutOfRangeException(nameof(resolution));
            if (colors == null)
                throw new ArgumentNullException(nameof(colors));
            if (colors.Length != checked(resolution * resolution))
                throw new ArgumentException("Unexpected color mip texel count.", nameof(colors));

            Resolution = resolution;
            _colors = colors;
        }

        public int Resolution { get; private set; }

        internal Color SampleNearest(float u, float v)
        {
            int x = Clamp((int)(u * Resolution), 0, Resolution - 1);
            int y = Clamp((int)(v * Resolution), 0, Resolution - 1);
            return _colors[y * Resolution + x];
        }

        static int Clamp(int value, int minimum, int maximum)
        {
            if (value < minimum)
                return minimum;
            if (value > maximum)
                return maximum;
            return value;
        }
    }

    /// <summary>
    /// Mipmapped six-face color cubemap generated by the cartography worker.
    /// Face order is the PlanetCubeFace enum order.
    /// </summary>
    public sealed class PlanetColorCubemap
    {
        readonly PlanetColorMip[][] _faces;

        internal PlanetColorCubemap(
            PlanetColorMip[][] faces,
            int requestedMaximumFaceSide)
        {
            if (faces == null || faces.Length != 6)
                throw new ArgumentException("A color cubemap must contain six faces.", nameof(faces));
            if (faces[0] == null || faces[0].Length == 0)
                throw new ArgumentException("A color cubemap must contain at least one mip.", nameof(faces));

            _faces = faces;
            BaseResolution = faces[0][0].Resolution;
            MipCount = faces[0].Length;
            RequestedMaximumFaceSide = requestedMaximumFaceSide;
        }

        public int BaseResolution { get; private set; }
        public int MipCount { get; private set; }

        /// <summary>
        /// The MaximumFaceSide value that produced this cubemap. Zero means the
        /// source planet-data resolution was requested.
        /// </summary>
        public int RequestedMaximumFaceSide { get; private set; }

        public bool IsFullResolution
        {
            get
            {
                // A finite request can still reach the source limit when the
                // planet-data faces are smaller than the requested side.
                return RequestedMaximumFaceSide <= 0 ||
                       BaseResolution < RequestedMaximumFaceSide;
            }
        }

        /// <summary>
        /// Returns true when this cubemap was generated at this request level or a
        /// more detailed one. A full-resolution cubemap satisfies every finite side.
        /// </summary>
        public bool SatisfiesFaceSide(int maximumFaceSide)
        {
            if (maximumFaceSide <= 0)
                return IsFullResolution;

            return IsFullResolution || RequestedMaximumFaceSide >= maximumFaceSide;
        }

        internal int DetailRank
        {
            get { return IsFullResolution ? int.MaxValue : RequestedMaximumFaceSide; }
        }

        /// <summary>
        /// Chooses the least detailed available mip that still meets or exceeds the
        /// number of samples projected across one cubemap face. This avoids visible
        /// undersampling while allowing a higher-resolution cubemap to service all
        /// lower zoom levels.
        /// </summary>
        public int SelectMipLevel(float projectedFaceSamples)
        {
            if (MipCount <= 1)
                return 0;

            projectedFaceSamples = Math.Max(1f, projectedFaceSamples);
            int selected = 0;

            for (int level = 0; level < MipCount; level++)
            {
                int resolution = _faces[0][level].Resolution;
                if (resolution < projectedFaceSamples)
                    break;

                selected = level;
            }

            return selected;
        }

        public int GetMipResolution(int mipLevel)
        {
            return _faces[0][ClampMipLevel(mipLevel)].Resolution;
        }

        public Color Sample(Vector3 direction, int mipLevel)
        {
            if (direction.LengthSquared() <= 1e-12f)
                return new Color(0, 0, 0, 0);

            direction.Normalize();
            PlanetCubeFace face;
            float u;
            float v;
            PlanetMapSource.DirectionToFaceUv(direction, out face, out u, out v);

            return SampleFace(face, u, v, mipLevel);
        }

        internal Color SampleFace(
            PlanetCubeFace face,
            float u,
            float v,
            int mipLevel)
        {
            PlanetColorMip[] levels = _faces[(int)face];
            return levels[ClampMipLevel(mipLevel)].SampleNearest(u, v);
        }

        int ClampMipLevel(int mipLevel)
        {
            if (mipLevel < 0)
                return 0;
            if (mipLevel >= MipCount)
                return MipCount - 1;
            return mipLevel;
        }
    }

    internal static class PlanetColorCubemapBuilder
    {
        public static PlanetColorCubemap Build(
            PaintedPlanetFaces painted,
            int requestedMaximumFaceSide,
            bool releasePaintedFaces,
            CartographyCancellation cancellation)
        {
            if (painted == null)
                throw new ArgumentNullException(nameof(painted));
            if (cancellation == null)
                throw new ArgumentNullException(nameof(cancellation));

            var faces = new PlanetColorMip[6][];
            for (int i = 0; i < PlanetMapSource.ExportOrder.Length; i++)
            {
                cancellation.ThrowIfCancelled();
                PlanetCubeFace face = PlanetMapSource.ExportOrder[i];
                RawRgbaBitmap bitmap = painted.Faces[face];
                faces[(int)face] = BuildMipChain(bitmap, cancellation);
                if (releasePaintedFaces)
                    painted.Faces.Remove(face);
            }

            return new PlanetColorCubemap(faces, requestedMaximumFaceSide);
        }

        static PlanetColorMip[] BuildMipChain(
            RawRgbaBitmap bitmap,
            CartographyCancellation cancellation)
        {
            if (bitmap == null)
                throw new ArgumentNullException(nameof(bitmap));
            if (bitmap.Width != bitmap.Height)
                throw new ArgumentException("Color cubemap faces must be square.", nameof(bitmap));

            int resolution = bitmap.Width;
            Color[] colors = ExtractColors(bitmap);
            var levels = new List<PlanetColorMip>();

            while (true)
            {
                cancellation.ThrowIfCancelled();
                levels.Add(new PlanetColorMip(resolution, colors));

                if (resolution == 1)
                    break;

                int nextResolution = Math.Max(1, resolution / 2);
                colors = Downsample(colors, resolution, nextResolution);
                resolution = nextResolution;
            }

            return levels.ToArray();
        }

        static Color[] ExtractColors(RawRgbaBitmap bitmap)
        {
            var colors = new Color[checked(bitmap.Width * bitmap.Height)];
            for (int y = 0; y < bitmap.Height; y++)
            {
                int sourceRow = y * bitmap.Stride;
                int destinationRow = y * bitmap.Width;
                for (int x = 0; x < bitmap.Width; x++)
                {
                    int source = sourceRow + x * 4;
                    colors[destinationRow + x] = new Color(
                        bitmap.Pixels[source],
                        bitmap.Pixels[source + 1],
                        bitmap.Pixels[source + 2],
                        bitmap.Pixels[source + 3]);
                }
            }

            return colors;
        }

        static Color[] Downsample(Color[] source, int sourceResolution, int targetResolution)
        {
            var result = new Color[checked(targetResolution * targetResolution)];

            for (int y = 0; y < targetResolution; y++)
            {
                int sourceY0 = y * sourceResolution / targetResolution;
                int sourceY1 = Math.Max(sourceY0 + 1, (y + 1) * sourceResolution / targetResolution);
                sourceY1 = Math.Min(sourceResolution, sourceY1);

                for (int x = 0; x < targetResolution; x++)
                {
                    int sourceX0 = x * sourceResolution / targetResolution;
                    int sourceX1 = Math.Max(sourceX0 + 1, (x + 1) * sourceResolution / targetResolution);
                    sourceX1 = Math.Min(sourceResolution, sourceX1);

                    int red = 0;
                    int green = 0;
                    int blue = 0;
                    int alpha = 0;
                    int count = 0;

                    for (int sy = sourceY0; sy < sourceY1; sy++)
                    {
                        int row = sy * sourceResolution;
                        for (int sx = sourceX0; sx < sourceX1; sx++)
                        {
                            Color color = source[row + sx];
                            red += color.R;
                            green += color.G;
                            blue += color.B;
                            alpha += color.A;
                            count++;
                        }
                    }

                    result[y * targetResolution + x] = new Color(
                        (byte)((red + count / 2) / count),
                        (byte)((green + count / 2) / count),
                        (byte)((blue + count / 2) / count),
                        (byte)((alpha + count / 2) / count));
                }
            }

            return result;
        }
    }
}
